//
// Created by maciej on 01.09.21.
//

#include "ngx_sslkeylog.h"
#define _GNU_SOURCE /* for RTLD_NEXT */
#include <dlfcn.h>
#include <fcntl.h>
#include <unistd.h>
#include <string.h>
#include <stdlib.h>
#include <stdio.h>

#define FIRSTLINE   "# SSL key logfile generated by ngx_keylog.c\n"
#define FIRSTLINE_LEN (sizeof(FIRSTLINE) - 1)

/* When building for OpenSSL 1.1.0 or newer, no headers are required. */
typedef struct ssl_st SSL;
typedef struct ssl_ctx_st SSL_CTX;

static int keylog_file_fd = -1;

static void open_keylog_file(const char *filename)
{
    keylog_file_fd = open(filename, O_WRONLY | O_APPEND | O_CREAT, 0644);
    if (keylog_file_fd >= 0 && lseek(keylog_file_fd, 0, SEEK_END) == 0) {
        /* file is opened successfully and there is no data (pos == 0) */
        write(keylog_file_fd, FIRSTLINE, FIRSTLINE_LEN);
    }
}

static void close_keylog_file(void)
{
    if (keylog_file_fd >= 0) {
        close(keylog_file_fd);
        keylog_file_fd = -1;
    }
}

static inline void *try_lookup_symbol(const char *sym, int optional)
{
    void *func = dlsym(RTLD_NEXT, sym);
    if (!func && optional && dlsym(RTLD_NEXT, "SSL_new")) {
        /* Symbol not found, but an old OpenSSL version was actually loaded. */
        return NULL;
    }
    /* Symbol not found, OpenSSL is not loaded (linked) so try to load it
     * manually. This is error-prone as it depends on a fixed library name.
     * Perhaps it should be an env name? */
    if (!func) {
        void *handle = dlopen(OPENSSL_SONAME, RTLD_LAZY);
        if (!handle) {
            fprintf(stderr, "Lookup error for %s: %s\n", sym, dlerror());
            abort();
        }
        func = dlsym(handle, sym);
        if (!func && !optional) {
            fprintf(stderr, "Cannot lookup %s\n", sym);
            abort();
        }
        dlclose(handle);
    }
    return func;
}

static inline void *lookup_symbol(const char *sym)
{
    return try_lookup_symbol(sym, 0);
}

/* Key extraction via the new OpenSSL 1.1.1 API. */
static void keylog_callback(const SSL *ssl, const char *line)
{
    if (keylog_file_fd >= 0) {
        write(keylog_file_fd, line, strlen(line));
        write(keylog_file_fd, "\n", 1);
    }
}

SSL *SSL_new(SSL_CTX *ctx)
{
    static SSL *(*func)();
    static void (*set_keylog_cb)();
    if (!func) {
        func = lookup_symbol(__func__);
        set_keylog_cb = lookup_symbol("SSL_CTX_set_keylog_callback");
    }
    /* Override any previous key log callback. */
    set_keylog_cb(ctx, keylog_callback);
    return func(ctx);
}
